trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install and build stage'
      inputs:
        script: |
          npm install
          npm run build-stage
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts: stage'
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)/s/dist'
        ArtifactName: 'stage'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Agent.BuildDirectory)/s/dist'
        Contents: '**/*'
    - task: CmdLine@2
      displayName: 'build production'
      inputs:
        script: |
          npm run build
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts: prod'
      inputs:
        PathtoPublish: '$(Agent.BuildDirectory)/s/dist'
        ArtifactName: 'prod'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

